---

# a) Instala o pacote do containerd
- name: Instalar containerd
  apt:
    name: containerd
    state: present
    update_cache: yes

# b) Cria o diretório de configuração, se não existir
- name: Criar diretório de configuração do containerd
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

# c) Gera o arquivo de configuração padrão do containerd
- name: Gerar arquivo padrão de configuração do containerd
  command: "containerd config default > /etc/containerd/config.toml"
  args:
    creates: /etc/containerd/config.toml

# d) Altera o cgroup driver para 'systemd' (obrigatório para o kubelet)
- name: Ajustar cgroup driver para systemd
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

# e) Reinicia e habilita o containerd
- name: Reiniciar e habilitar o containerd
  systemd:
    name: containerd
    enabled: yes
    state: restarted
