---
- name: Copiar script de join do control-plane
  copy:
    src: control-plane-join.sh
    dest: /home/vagrant/control-plane-join.sh
    owner: vagrant
    group: vagrant
    mode: 0755

- name: Inserir --apiserver-advertise-address no comando do join
  replace:
    path: /home/vagrant/control-plane-join.sh
    regexp: '^(.*kubeadm join.*)$'
    replace: '\1 --apiserver-advertise-address={{ ansible_host }}'
  become: true

- name: Executar script de join do control-plane
  command: /home/vagrant/control-plane-join.sh
  become: true
