---
# Executa o join do control-plane nos nós adicionais

- name: Copiar script de join do control-plane
  copy:
    src: control-plane-join.sh
    dest: /home/ansible/control-plane-join.sh
    owner: ansible
    group: ansible
    mode: 0755

- name: Executar script de join do control-plane
  command: /home/ansible/control-plane-join.sh
  become: true
