---
- name: Adicionar demais masters ao cluster
  hosts: control_planes:!master1
  become: true

  tasks:
    - name: Copiar comando de join de master1
      copy:
        src: /home/ansible/kubeadm_join_control_plane.sh
        dest: /home/ansible/kubeadm_join_control_plane.sh
      delegate_to: master1

  tasks:
    - name: Executar comando de join para control-plane
      shell: sh /home/ansible/kubeadm_join_control_plane.sh
