---
- name: Atualizar pacotes do sistema
  apt:
    update_cache: yes
    upgrade: dist
  become: true  

- name: Desativar o swap
  command: swapoff -a
  become: true

- name: Remover entradas de swap do fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*\sswap\s.*)$'
    replace: '# \1'
  become: true

- name: Instalar pacotes básicos
  apt:
    name: "{{ base_packages }}"
    state: present
  become: true

- name: Criar diretório para armazenar chaves APT, se não existir
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Baixar a chave pública do Kubernetes via shell
  ansible.builtin.shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  become: true

- name: Adicionar repositório do Kubernetes via shell
  ansible.builtin.shell: |
    echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /" > /etc/apt/sources.list.d/kubernetes.list
  args:
    creates: /etc/apt/sources.list.d/kubernetes.list
  become: true

- name: Atualizar cache do APT
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Instalar kubeadm, kubelet e kubectl
  apt:
    name: "{{ kube_packages }}"
    state: present
    update_cache: yes
  become: true 
