---
- name: Preparar nós para o Kubernetes
  hosts: k8s-all-nodes     
  become: true
  gather_facts: true

 
  roles:
    - containerd             
    - k8s-all-node   

- name: Configuração do nó k8s-HA
  hosts: loadbalancer
  become: true
  gather_facts: true

  roles:
    - k8s-HA           

- name: Configuração do nó master
  hosts: k8s-master-nodes   
  become: true
  gather_facts: true

  roles:
    - k8s-master-node       

- name: Configuração do nó control plane
  hosts: k8s-cplane-nodes   
  become: true
  gather_facts: true

  roles:
    - k8s-cplane-node        

- name: Configuração dos nós worker
  hosts: k8s-worker-nodes    
  become: true
  gather_facts: true

  roles:
    - k8s-worker-node        
