---
- name: Copiar script de join do worker
  copy:
    src: worker-join.sh
    dest: /home/vagrant/worker-join.sh
    owner: vagrant
    group: vagrant
    mode: 0755

- name: Executar script de join do worker
  command: /home/vagrant/worker-join.sh
  become: true
